# Generated by Django 4.2.3 on 2023-07-28 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_register', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='stud_code',
            new_name='studcode',
        ),
    ]
